apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  profile: default
  hub: "registry.fi.intel.com/xintongc"
  tag: "tcs"
  components:
    pilot:
      k8s:
        env:
          - name: CERT_SIGNER_DOMAIN
            value: tcsclusterissuer.tcs.intel.com
          - name: EXTERNAL_CA
            value: ISTIOD_RA_KUBERNETES_API
          - name: PILOT_CERT_PROVIDER
            value: k8s.io/tcsclusterissuer.tcs.intel.com/sgx-signer
        overlays:
          - kind: ClusterRole
            name: istiod-clusterrole-istio-system
            patches:
              - path: rules[-1]
                value: |
                  apiGroups:
                  - certificates.k8s.io
                  resourceNames:
                  - tcsclusterissuer.tcs.intel.com/*
                  resources:
                  - signers
                  verbs:
                  - approve
                  - get
                  - patch
                  - delete
                  - watch
                  - update
  meshConfig:
    defaultConfig:
      proxyMetadata:
        PROXY_CONFIG_XDS_AGENT: "true"
        ISTIO_META_CERT_SIGNER: sgx-signer
    caCertificates:
      - pem: |
          -----BEGIN CERTIFICATE-----
          MIIEbDCCAtSgAwIBAgIIQmTnPXrIE+swDQYJKoZIhvcNAQELBQAwVDEdMBsGA1UE
          ChMUSW50ZWwoUikgQ29ycG9yYXRpb24xMzAxBgNVBAMTKlNHWCBzZWxmLXNpZ25l
          ZCByb290IGNlcnRpZmljYXRlIGF1dGhvcml0eTAeFw0yMjEyMTIwNDU5MDlaFw0y
          MzEyMTIwNDU5MDlaMFQxHTAbBgNVBAoTFEludGVsKFIpIENvcnBvcmF0aW9uMTMw
          MQYDVQQDEypTR1ggc2VsZi1zaWduZWQgcm9vdCBjZXJ0aWZpY2F0ZSBhdXRob3Jp
          dHkwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQDMS1uyZxJj29UOLfKU
          ByazixHTJ03Co5QiD9Xtnz+K2UOgsBzudAS5vJvN36EvTYsuARCGtvroyN1upq9c
          yFjfuVVroqxvdWx7CLBL6IbbDRwRyRZ5ftZvGcfREVV2oWdNoR5xHLnNPtIsPpc3
          sUJYnXR2tmlSsYYtBJC8Lxrlr9pZqq66UrpE1vGlYH0eW8maFD1dUQWhtJFtxdXF
          guBdq3ozMPemots0Aq23kJufFqbUVIeoTv2d3VdgQpzyg/hwfejk0/hVHryE5TD7
          nB3CBEZsGjW48RUQKRUKLvJNfU4KA/r+g4QoVzhsH96EFW657Rtt2QxUvchm/4aI
          OdRJ7Gb34PcImOrRsBMjkBLZbN3NEGKG3CFm8b9l+I4HSauRtVffGtMcfh2V7ajF
          biqd1Vdtt6zCneC6u9LDweVyd7KN25pmoI8NcFwYD0mG8u7xtdxvso1Hk+3SczyB
          ymxFtELiW/L007w1/8wnZKzVxKmOP3rqkqdrFUQbN5Zt3wUCAwEAAaNCMEAwDgYD
          VR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFCw6ccwrJs/k
          3cl61fk+5dgXmHA8MA0GCSqGSIb3DQEBCwUAA4IBgQBu3oX9CQTvrpcAccSMZokg
          QHpEwllXaXpDieYGNQMNYQzDqEFyiPJ0pWMfRgGe1zMYj4wf2k/BhxaPFRIWWsPf
          ASETdqmlJJ0WPmmFlatKp60ufLfy8tHKRqlsy0KvBI/iiQbGH7iSgQ5/S4CwjiVi
          nBzbpSwDiuh2z549yD6dqJmbhBMxy+WpdCww4TyNY1ZvjSGSTjwQEucdyYrdlMdw
          6DZOV/4Ys8QAPcj0tKHgdSSCVH1AlO4/1/Ex7QN3drxRyCCKmpEezhFELBKRBYJz
          ox3SruNIfdo8/J6rS3LldHJtrRrIpR6+kpl6OU017Y1qLTN4fBghDl4zFTeLfjJY
          IR2yWk6YZEukmufi/uvXBA6gbjhXuvAjwIogNW7V49YHdljGsfYs0Rq8TbddfoVc
          4tKGWz/l/XNASBwufICbXZEuX46WdN/0x/B0j1vrvZ2FTbc8kNmIY6UNQA6Rmt68
          xvOLdsHZ9QWhg/iz1Jw3B7Njbc4K/qXMENzNPh2IsGU=
          -----END CERTIFICATE-----
        certSigners:
        - tcsclusterissuer.tcs.intel.com/sgx-signer
  values:
    global:
      imagePullPolicy: IfNotPresent
    sidecarInjectorWebhook:
      templates:
        sgx: |
          metadata:
            annotations:
              sgx.intel.com/quote-provider: aesmd
          spec:
            containers:
            - name: sdsserver
              image: registry.fi.intel.com/xintongc/sds-server:tcsv2
              imagePullPolicy: IfNotPresent
              lifecycle:
                postStart:
                  exec:
                    command: ["/bin/sh", "-c", "./home/istio-proxy/prepare.sh"]
              resources:
                limits:
                  cpu: 200m
                  memory: 500Mi
                  sgx.intel.com/enclave: 1
                  sgx.intel.com/epc: 1Mi
                requests:
                  cpu: 200m
                  memory: 300Mi
                  sgx.intel.com/enclave: 1
                  sgx.intel.com/epc: 1Mi    
              env:
              - name: NEED_QUOTE
                value: "true"
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: SERVICE_ACCOUNT
                valueFrom:
                  fieldRef:
                    fieldPath: spec.serviceAccountName
              {{- with (valueOrDefault .MeshConfig.TrustDomain .Values.global.trustDomain)  }}
              - name: TRUST_DOMAIN
                value: "{{ . }}"
              {{- end }}
              - name: CERT_SIGNER_DOMAIN
                value: tcsclusterissuer.tcs.intel.com
              - name: EXTERNAL_CA
                value: ISTIOD_RA_KUBERNETES_API
              - name: PILOT_CERT_PROVIDER
                value: k8s.io/tcsclusterissuer.tcs.intel.com/sgx-signer
              volumeMounts:
              - name: sds-server
                mountPath: /tmp/testsocket1
              - name: workload-socket
                mountPath: /var/run/secrets/workload-spiffe-uds
              - name: credential-socket
                mountPath: /var/run/secrets/credential-uds
              - name: sgx-libraries
                mountPath: /home/istio-proxy/sgx/lib
              - name: istio-podinfo
                mountPath: /etc/istio/pod
              - name: istio-token
                mountPath: /var/run/secrets/tokens
              - name: istiod-ca-cert
                mountPath: /var/run/secrets/istio
              - name: istio-data
                mountPath: /var/lib/istio/data
              - name: ctk-tokens
                mountPath: /opt/intel/cryptoapitoolkit/tokens
            - name: istio-proxy
              volumeMounts:
              - name: sds-server
                mountPath: /tmp/testsocket2
              - name: credential-socket
                mountPath: /var/run/secrets/credential-uds
              - name: sgx-libraries
                mountPath: /home/istio-proxy/sgx/lib
              - name: ctk-tokens
                mountPath: /opt/intel/cryptoapitoolkit/tokens
              resources:
                limits:
                  # cpu: 200m
                  # memory: 100Mi
                  sgx.intel.com/enclave: 1
                  sgx.intel.com/epc: 1Mi
                requests:
                  # cpu: 200m
                  # memory: 100Mi
                  sgx.intel.com/enclave: 1
                  sgx.intel.com/epc: 1Mi 
              env:
              - name: GREETING
                value: hello-world
            volumes:
            - name: sds-server
              hostPath: 
                path: /tmp/testsocket
                type: DirectoryOrCreate
            - emptyDir:
              name: workload-socket
            - emptyDir:
              name: credential-socket
            - emptyDir:
              name: sgx-libraries
            - emptyDir:
              name: ctk-tokens

