##################################################################################################
# Sleep service
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testuds
---
apiVersion: v1
kind: Service
metadata:
  name: testuds
  labels:
    app: testuds
    service: testuds
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: testuds
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testuds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testuds
  template:
    metadata:
      labels:
        app: testuds
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: testuds
      initContainers:
      - name: init
        command: ["/bin/touch", "/var/run/secrets/workload-spiffe-uds/socket.sock"]
        image: testuds:latest
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /var/run/secrets/workload-spiffe-uds
          name: sds-server
      containers:
      - name: testuds
        image: testuds:latest
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: Never
        volumeMounts:
        # - mountPath: "/tmp/sc"
        - mountPath: "/var/run/secrets/workload-spiffe-uds"
          name: sds-server
          readOnly: false
      - name: sds-server
        image: sds-server/sds-server:latest
        imagePullPolicy: Never
        volumeMounts:
        # - mountPath: "/tmp/sc"
        - mountPath: "/var/run/secrets/workload-spiffe-uds"
          name: sds-server
      volumes:
      - name: sds-server
        emptyDir: {}
---
