apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  profile: default
  hub: "istio"
  tag: "sgx-1122"
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_CERT_SIGNER: istio-system
    caCertificates:
      - pem: |
          -----BEGIN CERTIFICATE-----
          MIIDjTCCAnWgAwIBAgIUflG9UK6yXg9qY/jbLVMKr95ZDWwwDQYJKoZIhvcNAQEL
          BQAwVjELMAkGA1UEBhMCR0IxDzANBgNVBAcMBkxvbmRvbjEWMBQGA1UECgwNY2x1
          c3Rlci5sb2NhbDEeMBwGA1UEAwwVd3d3LmNsdXN0ZXIubG9jYWwuY29tMB4XDTIy
          MTEyMzA2MDEwNloXDTIzMTEyMzA2MDEwNlowVjELMAkGA1UEBhMCR0IxDzANBgNV
          BAcMBkxvbmRvbjEWMBQGA1UECgwNY2x1c3Rlci5sb2NhbDEeMBwGA1UEAwwVd3d3
          LmNsdXN0ZXIubG9jYWwuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
          AQEA0LTkl5e51NjHO6FyU3CrYN5tYsSoXbzFu6jnFxixoqZ+ub/hWR0tJx8CjlLG
          q12gL0qmQA2INLpV4CjQaCNYl6Je8kXTfBGddNCHyVRER+Ygjlec1hB2sAsJOv9d
          mi4m0fUtcqGppyUHx8ZUsmydrkMSQitqE1S8IRw41eVs2BHYmLm8t9LIvgBZX+T5
          hKPbg9rJN90cN3k3wvw7sUpn2QXkyuCcRPr75J1vfliStZN2UDwlFt+UjUd8npic
          NiKpm7k45hHsAwTusveV8ponOKcCLpnCcg+AU/p3ZCF9AcT53RM4pkquNkMr2ckb
          lkEPGgk1Cyy4w8osiiJaTuw5zwIDAQABo1MwUTAdBgNVHQ4EFgQUDsTPVhGa6Icg
          zXgsTsIILK7GpvIwHwYDVR0jBBgwFoAUDsTPVhGa6IcgzXgsTsIILK7GpvIwDwYD
          VR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAE0dMKnDJOqphEx3uxLlX
          2T4SOoiqzy2SFFMXCYp29e0EJT+rvzpZbyfMs+BSh8519Llt5nU430NK4Ldt2OA0
          GzP8cBlZvuMMlQ7ILjcj3VfP/quTxHQbdvey1xOhQCgdqbM+2cEoVNXdBE5xf+m8
          IqEcSuU8jLxgc8gwGOPyMogujgLu5hXH55zTHovd2Zh1c68bIY5j4Q91Pu0WuSHT
          aqueCcnfKnSALwwJbqVMg0Ib3qzUl2rmsHoUqxaJt+rC/nzOE9Pdb1nHPpqrN0iU
          bNikPzSBIpVCDL3B6cjbsYjcWm9sSQMapBIqDDbyjitz8tLHfCqG1WBPxHHgV9ix
          iQ==
          -----END CERTIFICATE-----
        certSigners:
        - clusterissuers.cert-manager.io/istio-system
  values:
    global:
      imagePullPolicy: IfNotPresent
    sidecarInjectorWebhook:
      templates:
        custom: |
          metadata:
            annotations:
              sgx.intel.com/quote-provider: aesmd
          spec:
            containers:
            - name: testsds
              image: sds-server/sds-server:latest
              imagePullPolicy: IfNotPresent
              command: ["bash", "-c", "sleep 5s; ls -la /home/istio-proxy/sgx/lib; ./sds/sds-server"]
              lifecycle:
                postStart:
                  exec:
                    command: ["/bin/sh", "-c", "./home/istio-proxy/prepare.sh"]
              resources:
                limits:
                  cpu: 200m
                  memory: 500Mi
                  sgx.intel.com/enclave: 1
                  sgx.intel.com/epc: 1Mi
                requests:
                  cpu: 200m
                  memory: 300Mi
                  sgx.intel.com/enclave: 1
                  sgx.intel.com/epc: 1Mi    
              env:
              - name: MOCKSDS
                value: mock-sds-server
              volumeMounts:
              - name: sds-server
                mountPath: /tmp/testsocket1
              - name: workload-socket
                mountPath: /var/run/secrets/workload-spiffe-uds
              - name: credential-socket
                mountPath: /var/run/secrets/credential-uds
              - name: sgx-libraries
                mountPath: /home/istio-proxy/sgx/lib
              - name: istio-podinfo
                mountPath: /etc/istio/pod
              - name: istio-token
                mountPath: /var/run/secrets/tokens
              - name: istiod-ca-cert
                mountPath: /var/run/secrets/istio
              - name: istio-data
                mountPath: /var/lib/istio/data
              - name: ctk-tokens
                mountPath: /opt/intel/cryptoapitoolkit/tokens
            - name: istio-proxy
              volumeMounts:
              - name: sds-server
                mountPath: /tmp/testsocket2
              - name: credential-socket
                mountPath: /var/run/secrets/credential-uds
              - name: sgx-libraries
                mountPath: /home/istio-proxy/sgx/lib
              - name: ctk-tokens
                mountPath: /opt/intel/cryptoapitoolkit/tokens
              resources:
                limits:
                  # cpu: 200m
                  # memory: 100Mi
                  sgx.intel.com/enclave: 1
                  sgx.intel.com/epc: 1Mi
                requests:
                  # cpu: 200m
                  # memory: 100Mi
                  sgx.intel.com/enclave: 1
                  sgx.intel.com/epc: 1Mi 
              env:
              - name: GREETING
                value: hello-world
            volumes:
            - name: sds-server
              hostPath: 
                path: /tmp/testsocket
                type: DirectoryOrCreate
            - emptyDir:
              name: workload-socket
            - emptyDir:
              name: credential-socket
            - emptyDir:
              name: sgx-libraries
            - emptyDir:
              name: ctk-tokens

