apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  # profile: minimal
  # hub: "istio"
  # tag: "latest"
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_CERT_SIGNER: istio-system
    caCertificates:
      - pem: |
          -----BEGIN CERTIFICATE-----
          MIIDFDCCAfygAwIBAgIRAMK/k/OwEAJEa45NOEw5etkwDQYJKoZIhvcNAQELBQAw
          FzEVMBMGA1UEAxMMaXN0aW8tc3lzdGVtMB4XDTIxMTIxMDA3NDg0MVoXDTIyMDMx
          MDA3NDg0MVowFzEVMBMGA1UEAxMMaXN0aW8tc3lzdGVtMIIBIjANBgkqhkiG9w0B
          AQEFAAOCAQ8AMIIBCgKCAQEAzv5KU6gvuWZnRvAtg6IHakT/YL5Cwvm5esemqTh/
          e4kI8dYOQRuD8B1nZ/eZY4iljbSUpeceV9K2/PQpbSECouDWbCzYH3v/cxUSk7za
          nLfrHRBXyA25dIIWDr/yKkmwWBJQHwWQAmKDANOlJic30Ki5AzAUIHQpFodErLSD
          L0M1dUVHhWB2erIGKZRzvB1AuzsQLORZY4I/W8zpLFs96L4ecjfBqTTNzcFoa4qK
          lrkkx0iduL1YloeLgIzHy6spzVRCVpdQ0RctPfcspR+YW0Nfgsy5GR6+adWYQp3V
          pBsloooSLG//30X7mmHi5yoAAmzNl9qiSzqB3M8fAVmPxQIDAQABo1swWTAOBgNV
          HQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUkXJ5NmCrDEl9
          O1L7jjXa7Ide5gUwFwYDVR0RBBAwDoIMaXN0aW8tc3lzdGVtMA0GCSqGSIb3DQEB
          CwUAA4IBAQB0/FMAg/Bf1mEaBbN14jLUHtHjnyeSd2fnLby1Yg79CIdQ0ffaWGJA
          6LA4G2DXYxScOBcoxokujx7mCHlHwHg6UxOsiTH7DlqjhIAn2dRt1A1WH9vOvQ5r
          j5TbvJeF9xgofRotIMeqTLtM3Ozcho2Yv5pqWyWJJkjTdkHuop0Q5jl8lDhF4rh1
          DAJwkDiUs0TtePeVeTaG6+28XOSz/WFqk7vCUJrRXU+nBH9nmRURLdfFJpirviZv
          LVDhhkjYP9dYARfl6lPN0CjuwvwkTsjCR3QUaJkHqG1qUb2RNGh6L4dIbvX8QKH1
          sZFKWfif1FC6pr1GLToH4L2s4zrD/u4Q
          -----END CERTIFICATE-----
        certSigners:
        - clusterissuers.cert-manager.io/istio-system
  values:
    global:
      imagePullPolicy: IfNotPresent
    sidecarInjectorWebhook:
      templates:
        custom: |
          spec:
            containers:
            - name: testsds
              image: sds-server/sds-server:latest
              imagePullPolicy: IfNotPresent
              lifecycle:
                postStart:
                  exec:
                    command: 
                    - sh
                    - "-c"
                    - |-
                      ./copylib.sh && /sds/sds-server wait
              env:
              - name: MOCKSDS
                value: mock-sds-server
              volumeMounts:
              - name: sds-server
                mountPath: /tmp/testsocket1
              - name: workload-socket
                mountPath: /var/run/secrets/workload-spiffe-uds
              - name: credential-socket
                mountPath: /var/run/secrets/credential-uds
              - name: sgx-libraries
                mountPath: /usr/local/libsgx
              - name: istio-podinfo
                mountPath: /etc/istio/pod
            - name: istio-proxy
              volumeMounts:
              - name: sds-server
                mountPath: /tmp/testsocket2
              - name: credential-socket
                mountPath: /var/run/secrets/credential-uds
              - name: sgx-libraries
                mountPath: /usr/local/libsgx
              env:
              - name: GREETING
                value: hello-world
            volumes:
            - name: sds-server
              hostPath: 
                path: /tmp/testsocket
                type: DirectoryOrCreate
            - emptyDir:
              name: workload-socket
            - emptyDir:
              name: credential-socket
            - emptyDir:
              name: sgx-libraries

